package areacode

var AreaCode = map[string][]string{
	"ae_az": []string{"Dubai (UAE)", "asia"},
	"ae_du": []string{"Dubai (UAE)", "asia"},
	"al":    []string{"Albania", "europe"},
	"au":    []string{"Australia", "oceania"},
	"aw":    []string{"Aruba", "north_america"},
	"bb":    []string{"Barbados", "north_america"},
	"bd":    []string{"Bangladesh", "asia"},
	"be":    []string{"Belgium", "europe"},
	"bg":    []string{"Bulgaria", "europe"},
	"bh":    []string{"Bahrain", "asia"},
	"bl":    []string{"Saint-Barthélemy", "europe"},
	"bm":    []string{"Bermuda Is.", "north_america"},
	"bo":    []string{"Bolivia", "south_america"},
	"br":    []string{"Brazil", "south_america"},
	"bs":    []string{"Bahamas", "north_america"},
	"by":    []string{"Belarus", "europe"},
	"bz":    []string{"Belize", "north_america"},
	"ca":    []string{"Canada", "north_america"},
	"ca_nb": []string{"New Brunswick (Canada)", "north_america"},
	"ca_nl": []string{"Newfoundland and Labrador (Canada)", "north_america"},
	"ca_ns": []string{"Nova Scotia (Canada)", "north_america"},
	"ca_pe": []string{"Prince Edward Island (Canada)", "north_america"},
	"ca_qc": []string{"Quebec (Canada)", "north_america"},
	"ch":    []string{"Switzerland", "europe"},
	"cw":    []string{"Curaçao", "north_america"},
	"cy":    []string{"Cyprus", "europe"},
	"de":    []string{"Germany", "europe"},
	"dk":    []string{"Denmark", "europe"},
	"do":    []string{"Dominican Republic", "north_america"},
	"es":    []string{"Spain", "europe"},
	"fi":    []string{"Finland", "europe"},
	"fr":    []string{"France", "europe"},
	"gb":    []string{"United Kingdom", "europe"},
	"gf":    []string{"French Guiana", "south_america"},
	"gg":    []string{"Guernsey", "europe"},
	"gi":    []string{"Gibraltar", "europe"},
	"gl":    []string{"Greenland", "south_america"},
	"gp":    []string{"Guadeloupe", "europe"},
	"gr":    []string{"Greece", "europe"},
	"hk":    []string{"Hongkong", "asia"},
	"hr":    []string{"Croatia", "europe"},
	"ie":    []string{"Ireland", "europe"},
	"il":    []string{"Israel", "asia"},
	"im":    []string{"Isle of Man", "europe"},
	"in":    []string{"India", "asia"},
	"ir":    []string{"Iran", "asia"},
	"is":    []string{"Iceland", "europe"},
	"je":    []string{"Jersey", "europe"},
	"jm":    []string{"Jamaica", "north_america"},
	"jp":    []string{"Japan", "asia"},
	"kh":    []string{"Cambodia", "asia"},
	"li":    []string{"Liechtenstein", "europe"},
	"lu":    []string{"Luxembourg", "europe"},
	"lv":    []string{"Latvia", "europe"},
	"md":    []string{"Moldova", "europe"},
	"me":    []string{"Montenegro", "europe"},
	"mf":    []string{"Saint Martin", "north_america"},
	"mm":    []string{"Burma", "asia"},
	"mq":    []string{"Martinique", "north_america"},
	"mt":    []string{"Malta", "europe"},
	"mu":    []string{"Mauritius", "africa"},
	"mx":    []string{"Mexico", "north_america"},
	"my":    []string{"Malaysia", "asia"},
	"nl":    []string{"Netherlands", "europe"},
	"no":    []string{"Norway", "europe"},
	"nz":    []string{"New Zealand", "oceania"},
	"pa":    []string{"Panama", "north_america"},
	"pk":    []string{"Pakistan", "asia"},
	"pl":    []string{"Poland", "europe"},
	"pm":    []string{"Saint Pierre and Miquelon", "north_america"},
	"pr":    []string{"Puerto Rico", "north_america"},
	"re":    []string{"Réunion", "africa"},
	"ro":    []string{"Romania", "europe"},
	"rw":    []string{"Rwanda", "africa"},
	"se":    []string{"Sweden", "europe"},
	"sg":    []string{"Singapore", "asia"},
	"si":    []string{"Slovenia", "europe"},
	"sk":    []string{"Slovakia", "europe"},
	"th":    []string{"Thailand", "asia"},
	"tj":    []string{"Tajikstan", "asia"},
	"tn":    []string{"Tunisia", "africa"},
	"to":    []string{"Tonga", "oceania"},
	"tz":    []string{"Tanzania", "africa"},
	"ua":    []string{"Ukraine", "europe"},
	"ug":    []string{"Uganda", "africa"},
	"us_ak": []string{"Alaska(US)", "north_america"},
	"us_al": []string{"Alabama(US)", "north_america"},
	"us_ar": []string{"Arkansas(US)", "north_america"},
	"us_az": []string{"Arizona(US)", "north_america"},
	"us_ca": []string{"California(US)", "north_america"},
	"us_co": []string{"Colorado(US)", "north_america"},
	"us_ct": []string{"Connecticut(US)", "north_america"},
	"us_dc": []string{"District of Columbia (US)", "north_america"},
	"us_de": []string{"Delaware(US)", "north_america"},
	"us_fl": []string{"Florida(US)", "north_america"},
	"us_ga": []string{"Georgia(US)", "north_america"},
	"us_hi": []string{"Hawaii(US)", "north_america"},
	"us_ia": []string{"Iowa(US)", "north_america"},
	"us_id": []string{"Idaho(US)", "north_america"},
	"us_in": []string{"Indiana(US)", "north_america"},
	"us_ks": []string{"Kansas(US)", "north_america"},
	"us_ky": []string{"Kentucky(US)", "north_america"},
	"us_la": []string{"Louisiana(US)", "north_america"},
	"us_ma": []string{"Massachusetts(US)", "north_america"},
	"us_md": []string{"Maryland(US)", "north_america"},
	"us_me": []string{"Maine(US)", "north_america"},
	"us_mi": []string{"Michigan(US)", "north_america"},
	"us_mn": []string{"Minnesota(US)", "north_america"},
	"us_mo": []string{"Missouri(US)", "north_america"},
	"us_ms": []string{"Mississippi(US)", "north_america"},
	"us_mt": []string{"Montana(US)", "north_america"},
	"us_nc": []string{"North Carolina(US)", "north_america"},
	"us_nd": []string{"North Dakota(US)", "north_america"},
	"us_ne": []string{"Nebraska(US)", "north_america"},
	"us_nh": []string{"New hampshire(US)", "north_america"},
	"us_nj": []string{"New jersey(US)", "north_america"},
	"us_nm": []string{"New mexico(US)", "north_america"},
	"us_nv": []string{"Nevada(US)", "north_america"},
	"us_ny": []string{"New York(US)", "north_america"},
	"us_oh": []string{"Ohio(US)", "north_america"},
	"us_ok": []string{"Oklahoma(US)", "north_america"},
	"us_or": []string{"Oregon(US)", "north_america"},
	"us_pa": []string{"Pennsylvania(US)", "north_america"},
	"us_ri": []string{"Rhode island(US)", "north_america"},
	"us_sc": []string{"South carolina(US)", "north_america"},
	"us_sd": []string{"South dakota(US)", "north_america"},
	"us_tn": []string{"Tennessee(US)", "north_america"},
	"us_tx": []string{"Texas(US)", "north_america"},
	"us_ut": []string{"Utah(US)", "north_america"},
	"us_va": []string{"Virginia(US)", "north_america"},
	"us_vt": []string{"Vermont(US)", "north_america"},
	"us_wa": []string{"Washington(US)", "north_america"},
	"us_wi": []string{"Wisconsin(US)", "north_america"},
	"us_wv": []string{"West Virginia(US)", "north_america"},
	"us_wy": []string{"Wyoming(US)", "north_america"},
	"vn":    []string{"Vietnam", "asia"},
	"vu":    []string{"Vanuatu", "oceania"},
	"yt":    []string{"Mayotte", "africa"},
	"za":    []string{"South Africa", "africa"},
}
